# Generated by Django 4.2.4 on 2023-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
