# Generated by Django 4.2.4 on 2023-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_criteria_weight_remove_subcriteria_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria_text',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='utility_func',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcriteria',
            name='subcriteria_text',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='subcriteria',
            name='utility_func',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='utility_func',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_text',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
