# Generated by Django 4.2.4 on 2023-11-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_product_price_product_ram_product_rom_product_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria_title',
            new_name='title',
        ),
    ]
