# Generated by Django 4.2.4 on 2023-11-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_criteria_text_criteria_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcriteria',
            old_name='subcriteria_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='subcriteria',
            old_name='subcriteria_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='variable_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='variable_title',
            new_name='title',
        ),
    ]
