# Generated by Django 4.2.4 on 2023-11-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rename_subcriteria_text_subcriteria_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='utility_func',
            new_name='func',
        ),
        migrations.RenameField(
            model_name='subcriteria',
            old_name='utility_func',
            new_name='func',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='utility_func',
            new_name='func',
        ),
    ]
