# Generated by Django 4.2.4 on 2023-11-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_utility_func_criteria_func_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.product')),
            ],
        ),
    ]
