# Generated by Django 4.2.4 on 2023-11-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_productstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductStats',
            new_name='ProductStat',
        ),
    ]
