# Generated by Django 4.2.4 on 2023-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_rename_productstats_productstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aux',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ProductStat',
        ),
    ]
